board/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

app_name = 'menu'

urlpatterns = [
    path('home', views.home, name="home"),
    path('board', views.board, name="board"),
    path('board_write', views.board_write, name="board_write"),
    path('board_insert', views.board_insert, name="board_insert"),
    path('board_view', views.board_view, name="board_view"),
    path('board_edit', views.board_edit, name="board_edit"),
    path('board_update', views.board_update, name="board_update"),
    path('board_delete', views.board_delete, name="board_delete"),
]

config/urls.py
import imp
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from board import views
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('home/', include('board.urls')),
    path('auth/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views
app_name = "user"
urlpatterns = [
    path('', views.login_view, name="home"),
    path("login", views.login_view, name="login"),
    path("signup", views.signup_view, name="signup"),
    path("logout", views.logout_view, name="logout"),
]

board/models.py
from django.db import models
from traitlets import default

# Create your models here.


class Board(models.Model):
    b_no = models.AutoField(db_column='b_no', primary_key=True)
    b_title = models.CharField(db_column='b_title', max_length=255)
    b_note = models.TextField(db_column='b_note',)
    b_writer = models.CharField(db_column='b_writer', max_length=50)
    parent_no = models.IntegerField(db_column='parent_no', default=0)
    b_count = models.IntegerField(db_column='b_count', default=0)
    b_date = models.DateTimeField(db_column='b_date',)
    b_number = models.IntegerField(db_column='b_number', default=1)

    class Meta:
        managed = False
        db_table = 'board'

    def __str__(self):
        return "제목 : " + self.b_title+", 작성자 : " + self.b_writer

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    pass

board/views.py
from django import template
from multiprocessing import context
from sqlite3 import Row
from django.shortcuts import redirect, render
from requests import Response
from django.core.paginator import Paginator
from board.models import Board
# Create your views here.

# request는 브라우저에서 클라이언트가 호출하면 이 request 객체가 들어옴


def home(request):
    return render(request, 'home.html')


def board(request):
    rsBoard = Board.objects.all()
    return render(request, "board_list.html", {
        'rsBoard': rsBoard
    })


def board_write(request):
    return render(request, "board_write.html")


def board_insert(request):
    btitle = request.GET['b_title']
    bnote = request.GET['b_note']
    bwriter = request.GET['b_writer']
    if btitle != "":
        rows = Board.objects.create(
            b_title=btitle, b_note=bnote, b_writer=bwriter)
        return redirect('/board')
    else:
        return redirect('board_write')


def board_view(request):
    bno = request.GET['b_no']
    rsDetail = Board.objects.filter(b_no=bno)

    return render(request, "board_view.html", {
        'rsDetail': rsDetail
    })


def board_edit(request):
    bno = request.GET['b_no']
    rsDetail = Board.objects.filter(b_no=bno)

    return render(request, "board_edit.html", {
        'rsDetail': rsDetail
    })


def board_update(request):
    bno = request.GET['b_no']
    btitle = request.GET['b_title']
    bnote = request.GET['b_note']
    bwriter = request.GET['b_writer']

    try:
        board = Board.objects.get(b_no=bno)
        if btitle != "":
            board.b_title = btitle
        if bnote != "":
            board.b_note = bnote
        if bwriter != "":
            board.b_writer = bwriter
        try:
            board.save()
            return redirect('board')
        except ValueError:
            return Response({"success": False, "msg": "에러입니다"})
    except ObjectDoesNotExist:
        return Response({"success": False, "msg": "게시글 없음"})


def board_delete(request):
    bno = request.GET['b_no']
    rows = Board.objects.get(b_no=bno).delete()

    return redirect('board')

users/views.py
import imp
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password
# Create your views here.


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            print("인증성공")
            login(request, user)
            return render(request, "home.html")
        else:
            print("인증실패")
    return render(request, "users/login.html")


def logout_view(request):
    logout(request)
    return redirect("/")


def signup_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        re_password = request.POST["re_password"]
        email = request.POST["email"]
        res_data = {}
        if password != re_password:
            res_data['error'] = "비밀번호가 다름"
        else:
            user = User.objects.create_user(username, email, password)
            user.save()
            return redirect("user:login")

    return render(request, "users/signup.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>
        {% block title %}
        게시판 예제
        {% endblock %}
    </title>

    <meta content="" name="description">

    <meta content="" name="keywords">
    <!-- Favicons -->
    <link href="{ % static 'assets/img/favicon.png' %} " rel="icon">
    <link href="{ % static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    {% block styles %}
    <link href="{ % static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{ % static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{ % static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
    <link href="{ % static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
    <link href="{ % static 'assets/vendor/remixicon/remixicon.css'%}" rel="stylesheet">
    <link href="{ % static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- =======================================================
  * Template Name: FlexStart - v1.9.0
  * Template URL: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>


    {% block body %}
    {% endblock %}

templates/board_edit.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

{% block body %}

{% include "navbar.html" %}

    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs">
          <div class="container">

            <div class="d-flex justify-content-between align-items-center">
              <h4>게시판 수정</h4>
              <ol>
                <li><a href="/">Home</a></li>
                <li><a href="/board">게시판</a></li>
                <li>수정</li>
              </ol>
            </div>

          </div>
        </section><!-- End Breadcrumbs -->

        <!-- ======= Services Section ======= -->
        <section id="services" class="services">
          <div class="container">

            <div class="section-title" data-aos="fade-up">
                <div style="margin:20px 0;text-align:center;">
                <h3>게시판 수정</h3>
                </div>
                {% if not rsDetail %}
                    <p class="text-center">내용이 없습니다! </p>
                {% endif %}
                <div style="margin:20px 0;">

                <form action="/board_update" id="frmBoard">
                {% for i in rsDetail %}
                    <input type="hidden" name="b_no" value="{{ i.b_no }}" >
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">제목</td>
                            <td width="80%" align="left"><input type="input" placeholder="제목" name="b_title" value="{{ i.b_title }}" style="width:100%;"></td>
                        </tr>
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">작성자</td>
                            <td width="80%" align="left"><input type="input" placeholder="작성자" name="b_writer" value="{{ i.b_writer }}"></td>
                        </tr>
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">내용</td>
                            <td width="80%" align="left"><textarea name="b_note" style="width:100%;" rows="5">{{ i.b_note }}</textarea></td>
                        </tr>
                        <tr style="height:60px;border-top:solid 1px #dddddd;" align="center">
                            <td width="100%" colspan="2">
                                <button class="btn btn-outline-success my-2 my-sm-0" style="margin-right:10px;" onclick="javascript:document.getElementById('frmBoard').submit();">저장</button>
                                <button class="btn btn-outline-success my-2 my-sm-0" style="margin-right:10px;" onclick="location.href='/board'">목록</button>
                            </td>
                        </tr>
                    </table>
                {% endfor %}
                </form>


            </div>

          </div>
        </section><!-- End Services Section -->

    </main><!-- End #main -->

    {% include "footer.html" %}

{% endblock %}

templates/board_list.html
{% extends "base.html" %}
{% load mathfilters %}
{% load static %}
{% block scripts %}
{{block.super}}
<script>

</script>
{% endblock %}

{% block body %}
{% include "navbar.html" %}

<main id="main">
    <section class="breadcrumbs">
        <div class="container">

            <ol>
                <li><a href="index.html">Home</a></li>
                <li>Portfolio Details</li>
            </ol>
            <h2>Portfolio Details</h2>

        </div>
    </section><!-- End Breadcrumbs -->
    <section id="services" class="services">

        <div class="container" data-aos="fade-up">
            <h2>Services</h2>

            <div style="margin:20px 0;text-align:right;">
                <button class="btn btn-outline-success my-2 my-sm-0" style="margin-right:10px;"
                    onclick="location.href='/board_write'">등록</button>
            </div>

            {% if not rsBoard %}
            <p class="text-center">내용이 없습니다! </p>
            {% endif %}

            <div style="margin:30px 0;">
                {% for i in rsBoard %}
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr style="border-style:solid 1px #531b1b;">
                        <!--.paginator.count|sub:i.b_no.start_index| sub:forloop.counter0|add:1 -->
                        <td width="8%" align="center">{{i.b_number|add:forloop.counter0}} </td>
                        <td width="42%" align="left"><a href="/board_view?b_no={{ i.b_no }}">{{ i.b_title }}</a></td>
                        <td width="10%" align="center">{{ i.b_writer }} </td>
                        <td width="20%" align="center">{{ i.b_date }} </td>
                        <td width="8%" align="center">{{ i.b_count }} </td>
                        <td width="12%" align="right" style="padding:5px 0;">
                        <a href="/board_delete?b_no={{ i.b_no }}" class="btn btn-outline-success">삭제</a>
                        </td>
                    </tr>
                </table>
                {% endfor %}
            </div>
        </div>

    </section><!-- End Services Section -->
</main>

{% include "footer.html" %}

{% endblock %}

templates/board_view.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

{% block body %}

{% include "navbar.html" %}

    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs">
          <div class="container">

            <div class="d-flex justify-content-between align-items-center">
              <h4>게시판 상세보기</h4>
              <ol>
                <li><a href="/">Home</a></li>
                <li><a href="/board">게시판</a></li>
                <li>상세보기</li>
              </ol>
            </div>

          </div>
        </section><!-- End Breadcrumbs -->

        <!-- ======= Services Section ======= -->
        <section id="services" class="services">
          <div class="container">

            <div class="section-title" data-aos="fade-up">

                <div style="margin:20px 0;text-align:center;">
                <h3>게시판 상세보기</h3>
                </div>
                {% if not rsDetail %}
                    <p class="text-center">내용이 없습니다! </p>
                {% endif %}

                {% for i in rsDetail %}
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">제목</td>
                            <td width="80%" align="left">{{ i.b_title }} </td>
                        </tr>
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">작성자</td>
                            <td width="80%" align="left">{{ i.b_writer }} </td>
                        </tr>
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">내용</td>
                            <td width="80%" align="left">{{ i.b_note }} </td>
                        </tr>
                        <tr style="height:60px;border-top:solid 1px #dddddd;" align="center">
                            <td width="100%" colspan="2">
                                <a href="/board_edit?b_no={{ i.b_no }}" class="btn btn-outline-success">수정</a>
                                <button class="btn btn-outline-success my-2 my-sm-0" style="margin-right:10px;" onclick="location.href='/board'">목록</button>
                            </td>
                        </tr>
                    </table>
                {% endfor %}

            </div>

          </div>
        </section><!-- End Services Section -->

    </main><!-- End #main -->

    {% include "footer.html" %}

{% endblock %}

templates/board_write.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

{% block body %}

{% include "navbar.html" %}

    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs">
          <div class="container">

            <div class="d-flex justify-content-between align-items-center">
              <h4>게시판 등록</h4>
              <ol>
                <li><a href="index.html">Home</a></li>
                <li><a href="/board">게시판</a></li>
                <li>등록</li>
              </ol>
            </div>

          </div>
        </section><!-- End Breadcrumbs -->

        <!-- ======= Services Section ======= -->
        <section id="services" class="services">
          <div class="container">

            <div class="section-title" data-aos="fade-up">
                <h3>게시판 등록</h3>

                <form action="/board_insert" id="frmBoard">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">제목</td>
                            <td width="80%" align="left"><input type="input" placeholder="제 목" name="b_title" style="width:100%;"></td>
                        </tr>
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">작성자</td>
                            <td width="80%" align="left"><input type="input" placeholder="작성자" name="b_writer"></td>
                        </tr>
                        <tr style="height:45px;border-top:solid 1px #dddddd;">
                            <td width="20%" align="center">내용</td>
                            <td width="80%" align="left"><textarea name="b_note" style="width:100%;" rows="5"></textarea></td>
                        </tr>
                        <tr style="height:45px;border-top:solid 1px #dddddd;" align="center">
                            <td width="100%" colspan="2">
                                <button class="btn btn-outline-success my-2 my-sm-0" style="margin-right:10px;" onclick="javascript:document.getElementById('frmBoard').submit();">저장</button>
                                <button class="btn btn-outline-success my-2 my-sm-0" style="margin-right:10px;" onclick="location.href='/board'">목록</button>
                            </td>
                        </tr>
                    </table>
                </form>

            </div>

          </div>
        </section><!-- End Services Section -->

    </main><!-- End #main -->

    {% include "footer.html" %}

{% endblock %}

templates/footer.html
{% load static %} 
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">

    <div class="footer-newsletter">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12 text-center">
                    <h4>Our Newsletter</h4>
                    <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                </div>
                <div class="col-lg-6">
                    <form action="" method="post">
                        <input type="email" name="email"><input type="submit" value="Subscribe">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-top">
        <div class="container">
            <div class="row gy-4">
                <div class="col-lg-5 col-md-12 footer-info">
                    <a href="index.html" class="logo d-flex align-items-center">
                        <img src="assets/img/logo.png" alt="">
                        <span>FlexStart</span>
                    </a>
                    <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita
                        valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
                    <div class="social-links mt-3">
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

                <div class="col-lg-2 col-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 col-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                    <h4>Contact Us</h4>
                    <p>
                        A108 Adam Street <br>
                        New York, NY 535022<br>
                        United States <br><br>
                        <strong>Phone:</strong> +1 5589 55488 55<br>
                        <strong>Email:</strong> info@example.com<br>
                    </p>

                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>플랫폼 팀</span></strong>.
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
{% block scripts %}
<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

<body>
    {% block body %}

    {% include "navbar.html" %}

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero d-flex align-items-center">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center">
                    <h1 data-aos="fade-up">게시판 만들기</h1>
                    <h2 data-aos="fade-up" data-aos-delay="400"></h2>
                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">
                            <a href="#about"
                                class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                                <span>바로가기</span>
                                <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>
                        
                    <h2 data-aos="fade-up" data-aos-delay="400">꾸준하게..</h2>
                    </div>
                    
                </div>
                <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                    <img src="{ % static 'assets/img/hero-img.png' %}" class="img-fluid" alt="">
                </div>
            </div>
        </div>

    </section><!-- End Hero -->


    <main id="main">
    </main>

    {% include "footer.html" %}
    {% endblock %}
</body>

templates/navbar.html
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

        <a href="{% url 'menu:home' %}" class="logo d-flex align-items-center">
            <img src="assets/img/logo.png" alt="">
            <span>장고로 만든 게시판</span>
        </a>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto active" href="{% url 'menu:home' %}">Home</a></li>
                <li><a class="nav-link scrollto" href="{% url 'menu:board' %}" onclick="testFuntion()">board</a></li>
                <li><a class="nav-link scrollto" href="http://www.globalintelligence.kr/">COP</a></li>
                <li><a class="getstarted scrollto" href="{% url 'user:logout' %}">로그아웃</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인 페이지</title>
    <link rel="stylesheet" href="{% static 'assets/css/login.css' %}">
</head>

<body>
    <dir class="box">

        <div class="main_title">코코팡의 홈페이지</div>
        <form action="" class="login" method="POST">
            {% csrf_token %}
            <div class="field">
                <input name="username" type="text" style="padding: 2px;" placeholder="아이디">
            </div>
            <div class="field">
                <input name="password" type="password" style="padding: 2px;" placeholder="비밀번호">
            </div>

            <div class="field">
                <input type="submit" style="padding: 2px;" value="Login">
            </div>
            <div class="signup-link">아이디가 없나요? <a href="{% url 'user:signup' %}">회원가입</a></div>
            <div class="pass-link"><a href="">비밀번호 찾기</a></div>
        </form>
    </dir>
</body>

</html>

users/templates/users/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입 페이지</title>
    <link rel="stylesheet" href="{% static 'assets/css/signup.css' %}">
</head>

<form action="#" class="signup" method="POST">
    {% csrf_token %}
    
    <dir class="box">
        
    <div class="main_title">회원가입</div>
        <div class="field">
            <input name="username" type="text"style="padding: 2px;" placeholder="아이디" required>
        </div>
        <div class="field">
            <input name="password" type="password" style="padding: 2px;"placeholder="비밀번호" required>
        </div>
        <div class="field">
            <input name="re_password" type="password" style="padding: 2px;"placeholder="비밀번호 확인" required>
        </div>
        <div class="field">
            <input name="email" type="email" style="padding: 2px;"placeholder="이메일" required>
        </div>
        <div class="field">
            <input type="submit" style="padding: 2px;"value="Signup">
        </div>
        {{error}}
    </dir>
</form>

</html>